version: '3'

services:
  app:
    container_name: gin
    image: golang:1.12.0-alpine
    volumes:
      - .:/go/src/app
    command: >
      sh -c "cd /go/src/app &&
      apk update &&
      apk add --no-cache git &&
      go get -u github.com/codegangsta/gin &&
      go get -u github.com/golang/dep/cmd/dep &&
      dep init ||
      dep ensure &&
      gin -i run"
    ports:
      - 3001:3001
