version: '3'

services:
  app:
    container_name: gin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app
      - /go/src/app/vendor
    ports:
      - 3001:3001
